server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    hikari:
      username: root
      password: root
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 30000
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC


mybatis:
  #config-location:
  mapper-locations: classpath*:mapper/*.xml
